// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmF1cZ4h7Cx600asE4a8E3UaiwgytmwQ0',
    appId: '1:424644119249:web:76e9be9f7ebabe42dfd3f0',
    messagingSenderId: '424644119249',
    projectId: 'chatbot-35d82',
    authDomain: 'chatbot-35d82.firebaseapp.com',
    storageBucket: 'chatbot-35d82.appspot.com',
    measurementId: 'G-P2ZP45DN53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATw4q7gnbau4Gmp4cNfhPkExNtwKR9Qp4',
    appId: '1:424644119249:android:4652913f2c01cde2dfd3f0',
    messagingSenderId: '424644119249',
    projectId: 'chatbot-35d82',
    storageBucket: 'chatbot-35d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLeWFsPmFY6lBGfH3yqlflDwo6_118_u8',
    appId: '1:424644119249:ios:c4de91c74fd10402dfd3f0',
    messagingSenderId: '424644119249',
    projectId: 'chatbot-35d82',
    storageBucket: 'chatbot-35d82.appspot.com',
    iosClientId: '424644119249-h2rbdt2m2rtlrt73g00gg7tr9dg0mpsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLeWFsPmFY6lBGfH3yqlflDwo6_118_u8',
    appId: '1:424644119249:ios:c4de91c74fd10402dfd3f0',
    messagingSenderId: '424644119249',
    projectId: 'chatbot-35d82',
    storageBucket: 'chatbot-35d82.appspot.com',
    iosClientId: '424644119249-h2rbdt2m2rtlrt73g00gg7tr9dg0mpsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmF1cZ4h7Cx600asE4a8E3UaiwgytmwQ0',
    appId: '1:424644119249:web:649f2268883d49abdfd3f0',
    messagingSenderId: '424644119249',
    projectId: 'chatbot-35d82',
    authDomain: 'chatbot-35d82.firebaseapp.com',
    storageBucket: 'chatbot-35d82.appspot.com',
    measurementId: 'G-C8QC6P2Y1P',
  );

}